### ISSUE TITLE
memory requirements for running the entire code

### ISSUE THREAD

**Issue by manotroll** [k3ng/k3ng_cw_keyer#102]
reading in some places he asks for a mega 2560 plus a much smaller esp32 r cheaper and has more memory
which cards can I run all the code on?
it seems that the nano was also indicated in another pdf

sorry for bad english i'm using translator

**Comment by FrugalGuy** [comment]
Looks like a support request. Those are handled at another location.  See issue #45.

**Comment by VK2EFL** [comment]
Within the Arduino family the Uno and Nano have just 32K of flash memory. You can not enable all the features and have it fit into a Uno or Nano. The Arduino Mega2560 has 256K of flash and it can fit all the features.
I don't know anything about the esp32.

**Comment by manotroll** [comment]
there is no way to load the rest in some way like micro sd?
since the mega is very big

**Comment by VK2EFL** [comment]
I agree, the Mega2560 is physically quite large, but it does have more flash, more RAM, more EEPROM, more interrupts and many more pins than a Uno or Nano. It is showing its age a little with no WiFi, no bluetooth, no ethernet etc.
There is no way that I am aware of to use a non motherboard flash store to hold code that gets executed.
If you want the keyer unit to act as a beacon, then it is possible to attach a SD card shield and then on that SD card store the text file that you want the beacon to transmit. But there is no way to actually store compiled code on the SD and run it.

**Comment by FrugalGuy** [comment]
Can this issue be closed?

**Comment by manotroll** [comment]
it may well close as it wasn't and a bug was a request

**Comment by FrugalGuy** [comment]
Hi, @manotroll .  You can close by adding a comment, and instead of clicking 'Comment', click 'Close and Comment'.
