### ISSUE TITLE
YAACW not connect to pc

### ISSUE THREAD

**Issue by ik6den** [k3ng/k3ng_cw_keyer#128]
Hello and sorry to me if I disturb,
i built yaacw to use it with winkeyer ( https://i1cra.briata.org/yaacwk/  )
the circuit works very well with his ps2 keyboard but does not connect to my pc. I use windows10 and CP2102 USB to UART TLL Module 6Pin Serial Converter Adapter "I also tested with
FT232RL 3.3V 5V FTDI Mini USB to TTL Serial UART Adapter Module
set serial port to 1200baud
software used is log4oM and QARtest   SO  win 7 and 10
in your opinion where am I wrong?
sorry for my english
best 73 de ik6den

**Comment by ik6den** [comment]
Risolto caricando versione la precedente

**Comment by federicobriata** [comment]
Hi @k3ng, can you close this issue?
The fix for have winkey working on Yaacwk was to upgrade from version 20180830 to 20190503.
thanks

**Comment by ik6den** [comment]
> Hello and sorry to me if I disturb, i built yaacw to use it with winkeyer ( https://i1cra.briata.org/yaacwk/ ) the circuit works very well with his ps2 keyboard but does not connect to my pc. I use windows10 and CP2102 USB to UART TLL Module 6Pin Serial Converter Adapter "I also tested with FT232RL 3.3V 5V FTDI Mini USB to TTL Serial UART Adapter Module set serial port to 1200baud software used is log4oM and QARtest SO win 7 and 10 in your opinion where am I wrong? sorry for my english best 73 de ik6den

After  upgrade the software k3ng_cw_keyer, without any modification to the electrical circuit, the device works very well on both log4OM and QARTEST, thanks Federico IZ1GLG for your help 
73's ik6den
