### ISSUE TITLE
Winkey support option

### ISSUE THREAD

**Issue by lefterists** [k3ng/k3ng_cw_keyer#14]
Please check line 6642:

if ((configuration.sidetone_mode == SIDETONE_ON) || (configuration.sidetone_mode == SIDETONE_PADDLE_ONLY)) {byte_to_send | 2;}

Shouldn't it be

if ((configuration.sidetone_mode == SIDETONE_ON) || (configuration.sidetone_mode == SIDETONE_PADDLE_ONLY)) {byte_to_send = byte_to_send | 2;}

73 de Lefteri

**Comment by k3ng** [comment]
Thanks!  This was fixed a few days ago. 73 Goody
