### ISSUE TITLE
WB6TOU Reported the need to install an additional library when using the 

### ISSUE THREAD

**Issue by flickerfly** [k3ng/k3ng_cw_keyer#20]
https://bitbucket.org/fmalpartida/new-liquidcrystal/downloads

**Comment by k3ng** [comment]
Thanks for the issue filling, however I can't figure out how this library fixed the user's issue.

**Comment by flickerfly** [comment]
Yeah, I haven't either. I was thinking about trying to duplicate, but haven't yet.
