### ISSUE TITLE
k3ng---Keypad

### ISSUE THREAD

**Issue by Idunbenhad** [k3ng/k3ng_cw_keyer#34]
Sorry, Anthony, but I have been unable to figure out generating a "PULL" on Github.  I have worked on it for hours now.  The dense just get denser, I guess.

I submitted the code for the keypad to you on your regular E:mail account.  If that's not satisfactory, I guess we can just drop it.

Sorry 'bout that

Jack-W0XR

**Comment by k3ng** [comment]
No worries, I can read it from the email and integrate it in.  73 Goody

**Comment by k3ng** [comment]
Closing as part of cleanup
