### ISSUE TITLE
FEATURE_COMMAND_MODE_PROGRESSIVE_5_CHAR_ECHO_PRACTICE - LCD Not cleared

### ISSUE THREAD

**Issue by gsansoucie** [k3ng/k3ng_cw_keyer#40]
I might be too quick to grab FEATURE_COMMAND_MODE_PROGRESSIVE_5_CHAR_ECHO_PRACTICE.

After entering the mode, the display shows the correct text about the practice, then reverts to the previous screen.  This might be FAD.

Down in 
void command_progressive_5_char_echo_practice()

There is:
 lcd.clear();
 
Which does clear the display, but doesn't set the state so the next call to service_display() restores the previous screen.

Calling lcd_clear() alleviates this.

Again, this might be FAD, but the text on the screen (From what I was sending previously) tripped me up a lot.

-Glen
(N1XF)

**Comment by k3ng** [comment]
Thanks, Glen.  This will be fixed on the next update.  73 Goody
