### ISSUE TITLE
Keying and decoding at the same time?

### ISSUE THREAD

**Issue by technoplusnl** [k3ng/k3ng_cw_keyer#41]
Hi,
Can anyone tell me if it should be possible to simultaneously decode what you send with the keyer if I use an Arduino Mega?

Thanks.
73, Albert PA3GUK

**Comment by k3ng** [comment]
Yes.  That's the paddle echo function.

**Comment by technoplusnl** [comment]
Thanks!

**Comment by k3ng** [comment]
You're welcome!  Hope you enjoy the keyer.

73
Goody
K3NG
