### ISSUE TITLE
WinKeyer Emulation (2) 'echo back' not working DXLab WinWarbler 

### ISSUE THREAD

**Issue by ng7m** [k3ng/k3ng_cw_keyer#52]
Goody, just adding this here for tracking... text from my original post on the main forum: In DXLab WinWarbler, you can setup the WinKeyer settings to do an echo back so you see the letters you are sending with the paddle, nice if someone is practicing.  What is happening in the latest code (or this issue has always existed) is that the echo back is sending the individual dits and dahs and not the letters.  So if I send a bunch of V's you see EEETEEET in the echo back from the Winkeyer Emulation instead of the letter V, or if you send a string of dits or dahs you see the whole string as e's or t's.  The only header file changes I have made is to select the Rev D nano keyer… no other defaults changed in the latest k3ng keyer code.  Here are a couple of images for reference.  Fixing this would just give it another level of compatibility to the actual Winkeyer.

**Comment by k3ng** [comment]
This has been fixed in the latest commit

https://github.com/k3ng/k3ng_cw_keyer/commit/986bbf72381fa25db14d82bb14d0d422b52ba588

Thanks for reporting! 
73
Goody
K3NG
