### ISSUE TITLE
Link on wiki main page to Schematics is broken

### ISSUE THREAD

**Issue by gareth8118** [k3ng/k3ng_cw_keyer#57]
Minor issue in wiki linkage: on this wiki page

https://github.com/k3ng/k3ng_cw_keyer/wiki

The link  to "Schematics" in the "Building" section needs to change from

https://github.com/k3ng/k3ng_cw_keyer/wiki/Build:-Schematic

to

https://github.com/k3ng/k3ng_cw_keyer/wiki/210-Build:-Schematic

**Comment by k3ng** [comment]
Fixed.  Thank you and 73!
