### ISSUE TITLE
Software question

### ISSUE THREAD

**Issue by sp9rqa** [k3ng/k3ng_cw_keyer#70]
Hello.
I am not a programmer, but after browsing the code I have a few questions because the compiler shows warnings.
Line 7428, declaration:
byte number_sent = 0;

and the comparison below:
if ((number_sent > -1) && (number_sent < 10))

but **byte**  it's an **typedef uint8 byte;**, so it's always bigger than a -1.
This is the case in several places.

It is similar in line 12674:
  byte memory_number = serial_get_number_input(2,0, (number_of_memories+1), port_to_use, RAISE_ERROR_MSG);

and the comparison below:
  if (memory_number > -1) {...}

the compiler informs you that this condition is always met.
I compile STM32F103.

73, Krzysztof

**Comment by k3ng** [comment]
You are correct.  This will be fixed in the next code update.

Thanks and 73!
Goody
K3NG
