### ISSUE TITLE
Winkey and  character P

### ISSUE THREAD

**Issue by ok1cdj** [k3ng/k3ng_cw_keyer#81]
Hello all, winkey emulation does not play  character P, completely ignore it. Tested with N1MM+ and WKTest by K1EL.
Any idea where is problem ?

73 Ondra

**Comment by k3ng** [comment]
Hello Ondra.  I can not reproduce this problem.  Are you sure you are typing an ASCII # 80 P character, or are you typing a non-English variant P ?

Also, can you tell me what features and options you have enabled?
